#!/usr/bin/perl

use strict;
use feature qw(:5.10);

use CGI;
use HTML::Template;

my $tmplDir = "/project/robodad/templates";
my $soundDir = "/project/robodad/sounds";
my $q = CGI->new;
my $armed = "/project/robodad/var/armed";

if ($q->param('sound')) {

	my $sound = $q->param('sound');

	system "mpg123 $soundDir/$sound.mp3";
	print $q->header;

} elsif ($q->param('armed')) {

	if ($q->param('armed') eq 1) {

		system "touch $armed";
	} else {
		unlink $armed;
	}
	print $q->header;

} else {
	startScreen();

}


#--------------------------------------------------
sub startScreen {
	print $q->header;

	my $tmplFile = "$tmplDir/home.tmpl";

	my $t = HTML::Template->new(
				filename 		=> $tmplFile,
				die_on_bad_params	=> 0,
			);

	my $tmplvars = {};

	if (-e $armed) {
		$tmplvars->{armed} = 1;

	}

	$t->param($tmplvars);

	print $t->output;

}
